name: SysWatch CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ── Job 1: Lint & Test ──────────────────────────────────────────────────────
  test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          # Fail on syntax errors or undefined names; warn on style issues
          flake8 syswatch.py --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 syswatch.py --count --max-line-length=100 --statistics

      - name: Run tests
        run: pytest tests/ -v

  # ── Job 2: Docker Build ─────────────────────────────────────────────────────
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: test           # Only build if tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t syswatch:ci .
          echo "✅ Docker build successful"

      - name: Smoke test Docker image
        run: |
          docker run --rm syswatch:ci python syswatch.py --json
          echo "✅ Smoke test passed"
